### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by selous123** [hendrycks/pre-training#1]
Hi, where can i get the pretrained models?

**Comment by hendrycks** [comment]
The adversarially trained Downsampled ImageNet model is here: https://drive.google.com/file/d/17dVIVfXind231eztRr0aWyl9YchvNN1x/view?usp=sharing

**Comment by selous123** [comment]
Thanks!

How about cifar10?

**Comment by hendrycks** [comment]
https://github.com/hendrycks/pre-training/tree/master/downsampled_train/snapshots/40_2
https://drive.google.com/drive/folders/1bqipqqZF8hTcEP4Kn0lb8TfH4Sny6ANX
