### ISSUE TITLE
How to remove CIFAR-10-related classes

### ISSUE THREAD

**Issue by hongxin001** [hendrycks/pre-training#2]
Hi, 
Could you share the dataset or the script for removing 153 CIFAR-10-related classes from the Downsampled ImageNet dataset?

**Comment by liyipeng00** [comment]
Thanks for your kind sharing of this code, which has helped me a lot with pre-training on imagenet32.

After searching this repo, I can not find the scripts for removing 153 CIFAR-10-related classes too. So could you provide the scripts or some links for solving it kindly.

Best wishes
