### ISSUE TITLE
Pretrained models for evaluating adversarial robustness

### ISSUE THREAD

**Issue by Gavin-1995** [hendrycks/pre-training#6]
Hi Hendrycks,

 I want to evaluate the adversarial robustness of your proposed method about the datasets CIFAR10 and CIFAR100, can you provide the pretrained models of the proposed method about these two datasets? 
 Thank you!

Best wishes,
Gavin

**Comment by hendrycks** [comment]
Hi,
https://github.com/hendrycks/pre-training/tree/master/robustness/adversarial
"Snapshots can be downloaded at https://drive.google.com/drive/folders/1bqipqqZF8hTcEP4Kn0lb8TfH4Sny6ANX?usp=sharing"
